# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  app_marcenaria-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: app_marcenaria-mysql
    volumes:
      - app_marcenaria-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=app_marcenaria
      - MYSQL_DATABASE=app_marcenaria
      - MYSQL_USER=app_marcenaria
      - MYSQL_PASSWORD=app_marcenaria

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: app_marcenaria-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
